# Generated by Django 2.2.3 on 2019-12-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_delete_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
